module: active-directory
name: heartbeat

transformation: true
aggregation: true
exclude_not_running_vm: true

signals:
  signal:
    metric: windows_ad_replication_sync_requests_total

rules:
  critical:
