matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      mode: html5
  sources:
  - '*.md'
  - 'docs/**/*.md|!docs/severity.md'
  - 'examples/**/*.md'
  - 'scripts/**/*.md'
  - 'scripts/**/*.md.j2'
  default_encoding: utf-8
