module: postfix
name: "Size Postfix Queue Hold"
id: "postfix_showq_message_size_bytes_count_hold"

transformation: ".min(over='30m')"
aggregation: true
filtering: "filter('queue', 'hold')"

signals:
  signal:
    metric: "postfix_showq_message_size_bytes_count"

rules:
  critical:
    threshold: 600
    comparator: ">"
    
  major:
    threshold: 300
    comparator: ">"
    dependency: "critical"
