module: squid
name: total amount of requests
id: total_requests

transformation: true
aggregation: true

signals:
  signal:
    metric: squid_client_http_requests_total

rules:
  critical:
    threshold: 1
    comparator: "<="
    lasting_duration: '5m'
