module: oracle
name: heartbeat

transformation: false
aggregation: ".mean(by=['hostname'])"

exclude_not_running_vm: true

signals:
  signal:
    metric: oracledb_Process_limits_value

rules:
  critical:
