module: oracle
name: "Database status"
id: dbisdown

transformation: true
aggregation: ".mean(by=['dbname','dbtype','hostname'])"

signals:
  signal:
    metric: oracledb_up
    rollup: latest

rules:
  critical:
    threshold: 1
    comparator: "<"
    lasting_duration: "5m"
    description: "is down"
tip: "oracle database is down, check status on server and logfile"


