module: oracle
name: "Pluggable database"
id: pdbisdown

transformation: true
aggregation: ".mean(by=['dbname','dbtype','hostname'])"

signals:
  signal:
    metric: oracledb_Pdb_is_up_count
    rollup: latest

rules:
  critical:
    threshold: 0
    comparator: ">"
    lasting_duration: "5m"     
    description: "is down"
tip: "The pluggable database is not started, check the status from the container database which manage it"
