module: oracle
name: pdbisdown

transformation: true
aggregation: true

signals:
  signal:
    metric: oracledb_Pdb_is_up_count

rules:
  critical:
    threshold: 0
    comparator: ">"
    lasting_duration: "5m"
