module: oracle
name: "fast recovery area usage"
id: fra_usage

transformation: true
aggregation: ".mean(by=['dbname','dbtype','hostname'])"

signals:
  signal:
    metric: oracledb_FRA_Usage_value
    rollup: max


rules:
  critical:
    threshold: 85
    comparator: ">"
    lasting_duration: "15m"
  major:
    threshold: 96
    comparator: ">"
    lasting_duration: "15m"
tip: "Oracle Fast recovery area is almost full, check archivelogs generation and deletion with rman backup. If needed and possible, check and change db_recovery_file_dest size"
