module: oracle
name: "fast recovery area usage"
id: fra_usage

transformation: true
aggregation: ".mean(by=['job'])"

signals:
  signal:
    metric: oracledb_FRA_Usage_value
    rollup: latest


rules:
  warning:
    threshold: 85
    comparator: ">"
    lasting_duration: "5m"
    description: "warning is reached"
  critical:
    threshold: 96
    comparator: ">"
    lasting_duration: "5m"
    description: "critical is reached"
