module: oracle
name: fra_usage

transformation: true
aggregation: true

signals:
  signal:
    metric: oracledb_FRA_Usage_value

rules:
  warning:
    threshold: 85
    comparator: ">"
    lasting_duration: "5m"
  critical:
    threshold: 96
    comparator: ">"
    lasting_duration: "5m"
