module: oracle
name: "number of sessions compared to limit"
id: sessions_limits

transformation: true
aggregation: ".mean(by=['dbname','dbtype','hostname'])"

signals:
  signal:
    metric: oracledb_Sessions_limits_value 
    rollup: latest

rules:
  critical:
    threshold: 85 
    comparator: ">"
    lasting_duration: "15m"
  major:
    threshold: 96
    comparator: ">"
    lasting_duration: "15m"
tip: "Oracle sessions usage are too close, if usage is 100% then the DB will not be accessible until sessions will be freed"
