module: oracle
name: "limit for sessions"
id: sessions_limits

transformation: true
aggregation: true

signals:
  signal:
    metric: oracledb_Sessions_limits_value 

rules:
  warning:
    threshold: 85 
    comparator: ">"
    lasting_duration: "5m"
    description: "warning is reached"
  critical:
    threshold: 96
    comparator: ">"
    lasting_duration: "5m"
    description: "critical is reached"
