module: oracle
name: "number of processes compared to limit"
id: process_limits

transformation: true
aggregation: ".mean(by=['dbname','dbtype','hostname'])"

signals:
  signal:
    metric: oracledb_Process_limits_value 
    rollup: latest

rules:
  critical:
    threshold: 85
    comparator: ">"
    lasting_duration: "15m"
  major:
    threshold: 96
    comparator: ">"
    lasting_duration: "15m"
tip: "Oracle server processes related to the database are too close, if usage is 100% then the DB will not be accessible until processes will be freed"
