module: oracle
name: Process_limits

transformation: true
aggregation: true

signals:
  signal:
    metric: oracledb_Process_limits_value 

rules:
  warning:
    threshold: 85
    comparator: ">"
    lasting_duration: "5m"
  critical:
    threshold: 96
    comparator: ">"
    lasting_duration: "5m"
