module: oracle
name: "gap in standby database replication"
id: STBY_Replication

transformation: true
aggregation: ".mean(by=['dbname','dbtype','hostname'])"

signals:
  signal:
    metric: oracledb_STBY_Replication_count 
    rollup: latest

rules:
  critical:
    threshold: 0
    comparator: ">"
    lasting_duration: "5m"
    description: "GAP detected"
tip: "GAP is detected on standby replication, check primary last sequence and standby. Also check logfiles"
