module: oracle
name: "tablespace usage on container database"
id: Tablespace_CDB

transformation: true
aggregation: true

signals:
  signal:
    metric: oracledb_tablespace_usage_pct_PDB_V2_real_ts_used_pct

rules:
  critical:
    threshold: 90
    comparator: ">"
    lasting_duration: "15m"
    decription: "usage % detected"
