module: oracle
name: "process dbvagent"
id: dbvagent

transformation: true
aggregation: true

signals:
  signal:
    metric: dbvagent

rules:
  critical:
    threshold: 1
    comparator: "<"
    lasting_duration: "5m"
    description: "is not started"
