module: oracle
name: "process dbvctl"
id: dbvctl

transformation: true
aggregation: true

signals:
  signal:
    metric: dbvctl

rules:
  critical:
    threshold: 1
    comparator: "<"
    lasting_duration: "5m"
    description: "is not started"
tip: "standby replication is not working"
