module: oracle
name: "process dbvctl"
id: dbvctl

transformation: true
aggregation: ".mean(by=['job'])"

signals:
  signal:
    metric: dbvctl
    rollup: latest

rules:
  critical:
    threshold: 1
    comparator: "<"
    lasting_duration: "5m"
    description: "is not started"
tip: "standby replication is not working"
