module: couchdb
name: couchdb_httpd_status_code_4xx

transformation: ".mean(over='10m')"
aggregation: ".sum(by=['sf_metric'])"

signals:
  A:
    metric: couchdb_httpd_status_codes
    filter: "(filter('code', '400', '401', '403', '404', '405', '406', '409', '412', '413', '414', '415', '416', '417'))"
    rollup: sum
  B:
    metric: couchdb_httpd_status_codes
    rollup: sum
  signal:
    formula: ((A/B).scale(100))
rules:
  critical:
    threshold: 30
    comparator: '>'
  major:
    threshold: 20
    comparator: '>'
    dependency: critical
