module: wallix-bastion
name: encryption status

transformation: true
aggregation: true

signals:
  status:
    metric: wallix_bastion_encryption_status
  signal:
    formula: status.fill(value=1)

rules:
  critical:
    threshold: 1
    comparator: "!="
    description: is not ready
