# This is a basic workflow to help you get started with Actions

name: Generator

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "claranet/terraform-ci:latest"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.4
        terraform_wrapper: false

    - name: test1
      run: echo $SHELL
    - name: test2
      run: type j2
    - name: test3
      run: "bash -c 'j2 --help'"
